### PR TITLE
Create 2014-12-31-calm-emotions.markdown

### PR DESCRIPTION
**Pull request by jayrab**
adding another 2nd level bard spell

### CODE REVIEW

**Comment by jayrab** [comment]
there are a few things that I dont understand about github and I am sure I am doing this in not the most ideal way, if you have some time to chat it would be helpful in moving forward.

**Comment by ephe** [comment]
Yeah totally! Will try to help as much as I can, but I'm far from an expert myself. Just lemme know when and over what!

**Comment by jayrab** [comment]
steam?

**Comment by ephe** [comment]
Steam works. What's your username?

**Comment by jayrab** [comment]
jay_rab

**Pull request merged**
